package com.matin.turbocar.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF00677D)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFB2EBFF)
val onPrimaryContainerLight = Color(0xFF001F27)
val secondaryLight = Color(0xFF4B626A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCEE6F0)
val onSecondaryContainerLight = Color(0xFF061E25)
val tertiaryLight = Color(0xFF904A47)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFDAD7)
val onTertiaryContainerLight = Color(0xFF3B0809)
val backgroundLight = Color(0xFFF5FAFD)

val primaryDark = Color(0xFF86D1E9)
val onPrimaryDark = Color(0xFF003642)
val primaryContainerDark = Color(0xFF004E5E)
val onPrimaryContainerDark = Color(0xFFB2EBFF)
val secondaryDark = Color(0xFFB3CAD3)
val onSecondaryDark = Color(0xFF1D343B)
val secondaryContainerDark = Color(0xFF344A52)
val onSecondaryContainerDark = Color(0xFFCEE6F0)
val tertiaryDark = Color(0xFFFFB3AE)
val onTertiaryDark = Color(0xFF571D1C)
val tertiaryContainerDark = Color(0xFF733331)
val onTertiaryContainerDark = Color(0xFFFFDAD7)